### ISSUE TITLE
Sneer removes last word from output if it ends in a newline with stdin

### ISSUE THREAD

**Issue by aThorp96** [JacobJustice/Sneer#6]
I believe this is due to 
```python
            if input[-1][-1] == '\n':
                input[-1] = args[-1][:-1] #remove \n
```

I am not sure why this is here, but if you try and sneer with just typing into stdin it must end in a newline, and the last word gets deleted unless you have a space between the last word and the newline.

**Comment by JacobJustice** [comment]
That is there because the intended output should not end in a newline like so

```
❰jacob❙~❱✔≻ cat file
test test test
❰jacob❙~❱✔≻ cat file | sneer
test Test tesT
❰jacob❙~❱✔≻ 
```
as opposed to:
```
❰jacob❙~❱✔≻ cat file
test test test
❰jacob❙~❱✔≻ cat file | sneer
test Test tesT

❰jacob❙~❱✔≻ 
```
That was my quick and dirty fix. 
I haven't encountered this issue personally could you show some examples?

**Comment by aThorp96** [comment]
Perhaps it needs to delete the last character instead of the last word. Running sneer without `cat` yields the following:
``` bash
$> sneer
this is a test
thIS iS A 
$> 
```
Putthing a space after the last word fixes this issue at the moment
``` bash
$> sneer
this is a test 
thIS iS A teSt
$> 
```

**Comment by aThorp96** [comment]
Update: This was an issue on my branch. It is fixed and the PR has been updated
